---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: karakeep-oauth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: karakeep-oauth-secret
    template:
      data:
        OAUTH_CLIENT_ID: "{{ .client_id }}"
        OAUTH_CLIENT_SECRET: "{{ .client_secret }}"
        OAUTH_WELLKNOWN_URL: "{{ .wellknown_url }}"
        OAUTH_PROVIDER_NAME: "{{ .provider_name }}"
  dataFrom:
    - extract:
        key: karakeep-oauth
