---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: karakeep
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: karakeep-secret
    template:
      data:
        MEILI_MASTER_KEY: "{{ .meili_master_key }}"
        NEXTAUTH_SECRET: "{{ .nextauth_secret }}"
        NEXT_PUBLIC_SECRET: "{{ .next_public_secret }}"
  dataFrom:
    - extract:
        key: karakeep
