---
apiVersion: kaniop.rs/v1beta1
kind: KanidmOAuth2Client
metadata:
  name: karakeep-app
spec:
  displayname: Karakeep
  image:
    url: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/karakeep.svg
  kanidmRef:
    name: sso
    namespace: sso
  origin: https://karakeep.siron.casa/
  redirectUrl:
    - https://karakeep.siron.casa/api/auth/callback/custom
  scopeMap:
    - group: karakeep
      scopes:
        - openid
        - profile
        - email
  jwtLegacyCryptoEnable: true
---
apiVersion: kaniop.rs/v1beta1
kind: KanidmGroup
metadata:
  name: karakeep
spec:
  kanidmRef:
    name: sso
    namespace: sso
  accountPolicy:
    authSessionExpiry: 2678400
  members:
    - sironheart
    - st-albus
