---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: &name sso-tls
spec:
  dnsNames:
    - sso.siron.casa
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  privateKey:
    algorithm: ECDSA
    size: 384
  secretName: *name
  usages:
    - digital signature
    - key encipherment
