---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: auth-credential-provider
spec:
  interval: 1h
  url: ssh://git@forgejo.siron.casa:22222/sironheart/auth-credential-users.git
  ref:
    branch: main
  secretRef:
    name: forgejo-auth-credential-provider
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: user-auth-repo
spec:
  interval: 1h
  prune: true
  sourceRef:
    kind: GitRepository
    name: auth-credential-provider
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-auth-credential-provider
spec:
  refreshInterval: 30m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: forgejo-auth-credential-provider
    template:
      type: Opaque
      engineVersion: v2
      data:
        identity: "{{ .privateKey }}"
        known_hosts: "[forgejo.siron.casa]:22222 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCm5D+DCmzlyXkG5dj0AtuvrVH3QSaUifKsggDy7bIYzq9lHOzxRzmx4I4xfDPyzHhD9WKMLbFiRK7YM/iXP2Hv0QAY8a5qLV+KQOPmpG7bRG8Br1aVWUWJnbOFCv13sBeiQKwwA8d5VGvsYplL+HWGF/RpD3iBXyg0Sxuub0g+SnmMBMHkeApjLYVIYfVv85tLLQXrpnC/ZxHcmUWAB34GeCxVbBmwbdDPQyIpo/z/YyCFzpWgOYY5U+6xErh7sd4N+qvsqLIywKIpwGrBtqj/jJpRxeZcMuqvXXSEZX3Kf7/1E7urAhle9/3ki4ZWljQuBYJSMMbTK/yg1fjxFpAulcQmi4mjOsk5WCL59enTZspohF8mqDKXgcLNyxrpUIbux/N1T84ytrTbBizZIrCzk2NGXmPQPu45zkDAYcQdSdJoJ14VhMH+AMT+Y62Bc6ARxOXn3jNoSGKIBye2tq9UJACligo04PuIAfcqpPRAxgO0u1JgNRUSrmlFm9QrEnJQ12ZM7Oxsr3ACIHbm2hrkBfdjcI+IkHPXC7Jg1b11VSMj3ywReHK4v33YqjnD1eKZ9E5y0vS59srsVjNka/J/ONN8/qdpRBP/e9fQaK73bRgw6FHnMfg+w8Wpor44hJ6E8zbRJnyargZH/Ad5/Qzqxn/nxeijhrVWO7Q+vw6fZQ=="
  data:
    - secretKey: privateKey
      remoteRef:
        key: ssh-deploy-token
        property: private key
