---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./backendtlspolicy.yaml
  - ./certificate.yaml
  - ./credentials-gitrepo.yaml
  - ./httproute.yaml
  - ./kanidm.yaml
