---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: memini
components:
  - ../../components/common
resources:
  - ./memini/ks.yaml
replacements:
  - path: ../../components/replacements/ks.yaml
