---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: &name postgres-server-ca
spec:
  isCA: true
  commonName: postgres-ca
  subject:
    countries:
      - DE
    organizations:
      - homelab-cluster
    organizationalUnits:
      - postgres
  usages:
    - cert sign
    - crl sign
  nameConstraints:
    critical: true
    permitted:
      dnsDomains:
        - .database.svc.cluster.local
        - .database.svc
        - postgres-rw
        - postgres-ro
        - postgres-r
  duration: 8760h # 1 year
  privateKey:
    algorithm: ECDSA
    size: 384
    encoding: PKCS8
    rotationPolicy: Never
  issuerRef:
    name: cluster-ca
    kind: ClusterIssuer
    group: cert-manager.io
  secretName: *name
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "cert-manager"
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: &name postgres-server-ca
spec:
  ca:
    secretName: *name
