---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: &name postgres
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: enabled
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  instances: 1

  # renovate: datasource=docker depName=ghcr.io/cloudnative-pg/postgresql
  imageName: ghcr.io/cloudnative-pg/postgresql:18.3-standard-trixie@sha256:9f9f53c9e07e5b2924945e6eaeb9168f7e856786d221839866ac85ccd703b3ba

  certificates:
    serverCASecret: postgres-server-cert
    serverTLSSecret: postgres-server-cert
    clientCASecret: postgres-client-ca
    replicationTLSSecret: postgres-client-cert

  storage:
    size: 10Gi
    storageClass: openebs-hostpath

  bootstrap:
    recovery:
      source: &src source
      recoveryTarget:
        targetTLI: "1"

  plugins:
    - name: &plugin barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: &store hetzner-store

  externalClusters:
    - name: *src
      plugin:
        name: *plugin
        parameters:
          barmanObjectName: *store
          serverName: postgres

  monitoring:
    enablePodMonitor: true

  postgresql:
    pg_hba:
      - hostssl all all all cert clientcert=verify-full map=pooler-map
    pg_ident:
      - pooler-map pooler-rw all

    shared_preload_libraries:
      - vchord.so
      - timescaledb
    parameters:
      timescaledb.telemetry_level: "off"
      max_locks_per_transaction: "128"

    extensions:
      - name: postgis
        ld_library_path:
          - system
        image:
          # renovate: datasource=docker depName=ghcr.io/cloudnative-pg/postgis-extension
          reference: ghcr.io/cloudnative-pg/postgis-extension:3.6.2-18-trixie@sha256:93584892e25a57e47e988b0f80ad9988035d1396d4a87824307eddf2242348c8

      - name: vchord
        image:
          # renovate: datasource=docker depName=ghcr.io/tensorchord/vchord-scratch
          reference: ghcr.io/tensorchord/vchord-scratch:pg18-v0.5.3@sha256:c310ede47f7f82bd257c3e53806d60680d5899c318ca946fb313efad9a90a78e
        dynamic_library_path:
          - /usr/lib/postgresql/18/lib
        extension_control_path:
          - /usr/share/postgresql/18/

      - name: timescaledb
        image:
          # renovate: datasource=docker depName=ghcr.io/shusaan/timescaledb-testing
          reference: ghcr.io/shusaan/timescaledb-testing:2.24.0-18-trixie@sha256:dae25c2dde06455214ac5553b51d3ef2d48fe84795c2cfa48c51c6e15877044e

  managed:
    roles:
      - name: pooler-rw
        ensure: present
        login: true
        superuser: false
        disablePassword: true
