---
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: pooler-rw
spec:
  cluster:
    name: postgres
  name: pooler-rw
  ensure: present
  login: true
  superuser: false
  disablePassword: true
  databaseRoleReclaimPolicy: delete
