---
serviceMonitor:
  create: true

web:
  httpRoute:
    enabled: true
    parentRefs:
      - name: internal
        namespace: network
    hostnames: ["flux.siron.casa"]

resources:
  limits:
    cpu: ~
    memory: 210Mi
  requests:
    cpu: 10m
    memory: 284Mi
