---
serviceMonitor:
  create: true

web:
  httpRoute:
    enabled: true
    parentRefs:
      - name: internal
        namespace: network
    hostnames: ["flux.siron.casa"]

resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 64Mi
