[env]
TALOSCONFIG = "{{config_root}}/k8s/talos/clusterconfig/talosconfig"
TOPFCONFIG = "{{config_root}}/k8s/talos/topf.yaml"
KUBECONFIG = "{{config_root}}/kubeconfig"

[tasks.talos-secrets]
run = "op inject -f -i {{config_root}}/op-templates/secrets.yaml.tpl -o {{config_root}}/k8s/talos/secrets.yaml"
description = "Uses the op-templates/secrets.yaml.tpl file and injects secrets from 1password"

[tasks.config-gen]
run = """
topf render -o {{config_root}}/k8s/talos/clusterconfig
topf talosconfig > {{config_root}}/k8s/talos/clusterconfig/talosconfig
chmod 600 {{config_root}}/k8s/talos/clusterconfig/talosconfig
"""
description = "Generate machine configs and talosconfig"
depends = ['talos-secrets']

[tasks.kubeconfig]
run = "talosctl kubeconfig -n internal.siron.casa $KUBECONFIG"
description = "Read the kubeconfig via talosctl"

[tasks.init]
depends = ['talos-secrets', 'config-gen']
description = "Setup project for local use"

[tasks.prepare-cluster]
depends = ['kubeconfig', 'install-crds', 'install-required-services']
description = "Install CRDs and basic tools"

[tasks.install-crds]
depends = ['kubeconfig']
run = "helmfile -q template -f bootstrap/helmfile.d/00-crds.yaml | yq ea -e 'select(.kind == \"CustomResourceDefinition\")' | kubectl apply --server-side -f - || true"
description = "Install all CRDs"
dir = "{{ config_root }}"

[tasks.install-required-services]
depends = ['kubeconfig', 'install-crds']
run = "helmfile sync -f bootstrap/helmfile.d/01-basic-installation.yaml"
description = "Install all required tools to have any running service"
dir = "{{ config_root }}"

[tools]
# Flux
flux2 = "2.9.5"

# Kubernetes
helm = "4.2.4"
helmfile = "1.7.4"
kubectl = "1.37.0"
kustomize = "5.8.1"

# Talos
talosctl = "1.14.0"
"github:postfinance/topf" = "0.5.0"
