[env]
TALOSCONFIG = "{{config_root}}/talos/clusterconfig/talosconfig"
TALHELPER_SECRETS = "{{config_root}}/talos/talsecret.yaml"
KUBECONFIG = "{{config_root}}/kubeconfig"

[tasks.talos-secrets]
run = "op inject -f -i {{config_root}}/op-templates/talsecret.yaml.tpl -o {{config_root}}/talos/talsecret.yaml"
description = "Uses the op-templates/talsecret.yaml.tpl file and injects secrets from 1password"

[tasks.config-gen]
run = "talhelper genconfig -s {{config_root}}/talos/talsecret.yaml -c {{config_root}}/talos/talconfig.yaml -o {{config_root}}/talos/clusterconfig"
description = "Generate machine configs"
depends = ['talos-secrets']

[tasks.kubeconfig]
run = "talosctl kubeconfig -n internal.siron.casa $KUBECONFIG"
description = "Read the kubeconfig via talosctl"

[tasks.init]
depends = ['talos-secrets', 'config-gen']
description = "Setup project for local use"

[tasks.prepare-cluster]
depends = ['kubeconfig', 'install-crds', 'install-required-services']
description = "Install CRDs and basic tools"

[tasks.install-crds]
depends = ['kubeconfig']
run = "helmfile template -f bootstrap/helmfile.d/00-crds.yaml | kubectl apply -f - || true"
description = "Install all CRDs"
dir = "{{ config_root }}"

[tasks.install-required-services]
depends = ['kubeconfig']
run = "helmfile sync -f bootstrap/helmfile.d/01-basic-installation.yaml"
description = "Install all required tools to have any running service"
dir = "{{ config_root }}"

[tools]
# Flux
flux2 = "2.7.5"

# Kubernetes
cilium-cli = "0.18.8"
helm = "4.0.4"
helmfile = "1.2.2"
kubectl = "1.35.0"
kustomize = "5.8.0"

# Talos
talhelper = "3.0.42"
talos = { version = "1.11.5", exe = "talosctl" }
