[env]
TALOSCONFIG = "{{config_root}}/talos/clusterconfig/talosconfig"
TALHELPER_SECRETS = "{{config_root}}/talos/talsecret.yaml"
KUBECONFIG = "{{config_root}}/kubeconfig"

[tasks.talos-secrets]
run = "op inject -f -i {{config_root}}/op-templates/talsecret.yaml.tpl -o {{config_root}}/talos/talsecret.yaml"
description = "Uses the op-templates/talsecret.yaml.tpl file and injects secrets from 1password"

[tasks.config-gen]
run = "talhelper genconfig -s {{config_root}}/talos/talsecret.yaml -c {{config_root}}/talos/talconfig.yaml -o {{config_root}}/talos/clusterconfig"
description = "Generate machine configs"
depends = ['talos-secrets']

[tasks.kubeconfig]
run = "talosctl kubeconfig -n talos.home $KUBECONFIG"
description = "Read the kubeconfig via talosctl"

[tasks.init]
depends = ['talos-secrets', 'config-gen']
description = "Setup project for local use"

[tools]
# Flux
"flux2" = "2.6.4"

# Kubernetes
"kubectl" = "1.33.3"
"kustomize" = "5.7.1"
"helm" = "3.18.4"
"helmfile" = "1.1.3"

# Talos
"talos" = "1.10.5"
"talhelper" = "3.0.32"
