---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: system-upgrade
components:
  - ../../../k8s-components/common
resources:
  - ./tuppr/ks.yaml
replacements:
  - path: ../../../k8s-components/replacements/ks.yaml
