---
apiVersion: kaniop.rs/v1beta1
kind: KanidmOAuth2Client
metadata:
  name: jellyfin-app
spec:
  displayname: Jellyfin
  image:
    url: https://cdn.jsdelivr.net/gh/selfhst/icons@main/png/jellyfin.png
  kanidmRef:
    name: sso
    namespace: sso
  origin: https://jellyfin.siron.casa/
  redirectUrl:
    - https://jellyfin.siron.casa/sso/OID/redirect/kanidm
  preferShortUsername: true
  scopeMap:
    - group: jellyfin
      scopes:
        - openid
        - profile
        - email
        - groups
