---
apiVersion: v1
kind: ConfigMap
metadata:
  name: languagetool-logback
data:
  logback.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <configuration>

      <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
          <pattern>{"timestamp":"%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX,UTC}","level":"%level","logger":"%logger{36}","thread":"%thread","message":"%replace(%replace(%replace(%replace(%replace(%msg){'[\x5c]','\\\\'}){'\"','\\\"'}){'\n','\\n'}){'\t','\\t'}){'\r','\\r'}","exception":"%replace(%replace(%replace(%replace(%replace(%exception{20}){'[\x5c]','\\\\'}){'\"','\\\"'}){'\n','\\n'}){'\t','\\t'}){'\r','\\r'}"}%n</pattern>
        </encoder>
      </appender>

      <appender name="METRICS" class="org.languagetool.server.InstrumentedAppender" />

      <logger name="org.languagetool" level="INFO"/>
      <!--  <logger name="org.languagetool.server.UserDictMapper" level="TRACE" />-->
      <!--  <logger name="org.languagetool.server.GroupMapper" level="TRACE" />-->

      <root level="info">
        <appender-ref ref="STDOUT" />
        <appender-ref ref="METRICS" />
      </root>
    </configuration>
