---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - ./kube-prometheus-stack/ks.yaml
  - ./grafana/ks.yaml
  - ./smartctl-exporter/ks.yaml
  - ./victoria-metrics/ks.yaml
components:
  - ../../../k8s-components/common
replacements:
  - path: ../../../k8s-components/replacements/ks.yaml
