---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - ./grafana/ks.yaml
  - ./smartctl-exporter/ks.yaml
  - ./victoria-metrics/ks.yaml
components:
  - ../../components/common
replacements:
  - path: ../../components/replacements/ks.yaml
