---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
# openapi:
#   path: http://crd-patcher.default.svc/definitions.json?crd=helm.toolkit.fluxcd.io.v2.HelmRelease&extraProp=helm.toolkit.fluxcd.io.v2.HelmRelease:spec.values.defaultPodOptions.schedulingGates
patches:
  - target:
      kind: HelmRelease
      group: helm.toolkit.fluxcd.io
      version: v2
    patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: not-used
      spec:
        values:
          persistence:
            postgres-certs:
              type: custom
              globalMounts:
                - path: /var/run/secrets/postgresql
              volumeSpec:
                csi:
                  driver: csi.cert-manager.io
                  readOnly: true
                  volumeAttributes:
                    csi.cert-manager.io/issuer-name: postgres-client-ca
                    csi.cert-manager.io/issuer-kind: ClusterIssuer
                    csi.cert-manager.io/key-algorithm: ${DATABASE_KEY_ALGORITHM:=ECDSA}
                    csi.cert-manager.io/key-size: ${DATABASE_KEY_SIZE:="384"}
                    csi.cert-manager.io/key-encoding: ${DATABASE_KEY_ENCODING:=PKCS8}
                    csi.cert-manager.io/key-usages: client auth
                    csi.cert-manager.io/common-name: ${APP}
                    csi.cert-manager.io/dns-names: $${POD_NAME}.$${POD_NAMESPACE}.svc.cluster.local
            root-ca:
              type: configMap
              name: root-ca
              defaultMode: 0440
              globalMounts:
                - path: /var/run/secrets/root-ca
