---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: penpot
# components:
#   - ../../components/common
resources: []
#   - ./penpot/ks.yaml
# replacements:
#   - path: ../../components/replacements/ks.yaml
