---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bookorbit
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: bookorbit-secret
    template:
      data:
        JWT_SECRET: "{{ .jwt_secret }}"
        SETUP_BOOTSTRAP_TOKEN: "{{ .setup_bootstrap_token }}"
        EMAIL_ENCRYPTION_KEY: "{{ .email_encryption_key }}"
        MIGRATION_ENCRYPTION_KEY: "{{ .migration_encryption_key }}"
  dataFrom:
    - extract:
        key: bookorbit