---
apiVersion: kaniop.rs/v1beta1
kind: KanidmOAuth2Client
metadata:
  name: bookorbit-app
spec:
  displayname: BookOrbit
  kanidmRef:
    name: sso
    namespace: sso
  image:
    url: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/bookorbit.svg
  origin: https://books.siron.casa
  redirectUrl:
    - https://books.siron.casa/oauth2-callback
  scopeMap:
    - group: bookorbit
      scopes:
        - openid
        - profile
        - email
        - groups
---
apiVersion: kaniop.rs/v1beta1
kind: KanidmGroup
metadata:
  name: bookorbit
spec:
  kanidmRef:
    name: sso
    namespace: sso
  accountPolicy:
    authSessionExpiry: 2678400
  members:
    - sironheart
