---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: memini-openai
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: memini-openai-secret
    template:
      data:
        MEMINI_EMBED_API_KEY: "{{ .openai_api_key }}"
  dataFrom:
    - extract:
        key: memini
