---
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: ${OWNER}
spec:
  cluster:
    name: postgres
  name: ${OWNER}
  ensure: present
  login: true
  superuser: ${SUPERUSER}
  disablePassword: true
  databaseRoleReclaimPolicy: delete
