---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: seerr-postgres
spec:
  deletionPolicy: Delete
  refreshInterval: 5m
  updatePolicy: Replace
  secretStoreRefs:
    - name: onepassword
      kind: ClusterSecretStore
  selector:
    secret:
      name: seerr-postgres
  data:
    - match:
        secretKey: url
        remoteRef:
          remoteKey: seerr-postgres
          property: url
    - match:
        secretKey: host
        remoteRef:
          remoteKey: seerr-postgres
          property: host
    - match:
        secretKey: port
        remoteRef:
          remoteKey: seerr-postgres
          property: port
    - match:
        secretKey: user
        remoteRef:
          remoteKey: seerr-postgres
          property: user
    - match:
        secretKey: db_name
        remoteRef:
          remoteKey: seerr-postgres
          property: db_name
    - match:
        secretKey: ssl_ca
        remoteRef:
          remoteKey: seerr-postgres
          property: ssl_ca
    - match:
        secretKey: ssl_key
        remoteRef:
          remoteKey: seerr-postgres
          property: ssl_key
    - match:
        secretKey: ssl_cert
        remoteRef:
          remoteKey: seerr-postgres
          property: ssl_cert
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seerr-db
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: seerr-db-secret
    template:
      data:
        DB_TYPE: postgres
        DB_USE_SSL: "true"
        DB_SSL_REJECT_UNAUTHORIZED: "true"
        DB_HOST: "{{ .host }}"
        DB_PORT: "{{ .port }}"
        DB_USER: "{{ .user }}"
        DB_NAME: "{{ .db_name }}"
        DB_SSL_CA_FILE: "{{ .ssl_ca }}"
        DB_SSL_KEY_FILE: "{{ .ssl_key }}"
        DB_SSL_CERT_FILE: "{{ .ssl_cert }}"

  dataFrom:
    - extract:
        key: seerr-postgres
