---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: seerr-postgres
spec:
  deletionPolicy: Delete
  refreshInterval: 5m
  updatePolicy: Replace
  secretStoreRefs:
    - name: onepassword
      kind: ClusterSecretStore
  selector:
    secret:
      name: seerr-postgres
  data:
    - match:
        secretKey: url
        remoteRef:
          remoteKey: seerr-postgres
          property: url
    - match:
        secretKey: host
        remoteRef:
          remoteKey: seerr-postgres
          property: host
    - match:
        secretKey: port
        remoteRef:
          remoteKey: seerr-postgres
          property: port
    - match:
        secretKey: user
        remoteRef:
          remoteKey: seerr-postgres
          property: user
    - match:
        secretKey: db_name
        remoteRef:
          remoteKey: seerr-postgres
          property: db_name
    - match:
        secretKey: ssl_ca
        remoteRef:
          remoteKey: seerr-postgres
          property: ssl_ca
    - match:
        secretKey: ssl_key
        remoteRef:
          remoteKey: seerr-postgres
          property: ssl_key
    - match:
        secretKey: ssl_cert
        remoteRef:
          remoteKey: seerr-postgres
          property: ssl_cert
