---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app gotosocial
spec:
  components:
    - ../../../../components/database
    - ../../../../components/kopiur
  dependsOn:
    - name: instance
      namespace: database
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 1h
  path: ./k8s/apps/mastodon/gotosocial/server
  postBuild:
    substitute:
      APP: *app
      KOPIUR_CAPACITY: 10Gi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 5m
  wait: false
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: phanpy
spec:
  interval: 1h
  path: ./k8s/apps/mastodon/gotosocial/phanpy
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: selfhosted
  timeout: 5m
  wait: false
