---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unifi-poller
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: unifi-poller-secret
    template:
      data:
        UP_UNIFI_DEFAULT_USER: "{{ .username }}"
        UP_UNIFI_DEFAULT_PASS: "{{ .password }}"
        UP_UNIFI_DEFAULT_URL: "{{ .url }}"
  dataFrom:
    - extract:
        key: unifi-poller
