---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: krr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: krr
    template:
      data:
        GITHUB_TOKEN: "{{ .githubTokenSironheart }}"
  dataFrom:
    - extract:
        key: renovate
