---
originRequest:
  originServerName: "cftunnel.siron.casa"

ingress:
  - hostname: "siron.casa"
    service: &svc https://cilium-gateway-external.kube-system.svc.cluster.local
  - hostname: "*.siron.casa"
    service: *svc
  - service: http_status:404
