---
apiVersion: v1
kind: ConfigMap
metadata:
  name: longhorn-default-resource
  namespace: longhorn-system
data:
  default-resource.yaml: |
    "backup-target": "s3://volsync-backups@auto/backup"
    "backup-target-credential-secret": "longhorn-backup-secret"
    "backupstore-poll-interval": "600"
