---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: grafana-admin-secret
    template:
      data:
        admin-user: "{{ .username }}"
        admin-password: "{{ .password }}"
  dataFrom:
    - extract:
        key: grafana
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-oauth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: auth-generic-oauth-secret
    template:
      data:
        client_id: "{{ .client_id }}"
        client_secret: "{{ .client_secret }}"
  dataFrom:
    - extract:
        key: grafana-oauth
