---
apiVersion: garage.rajsingh.info/v1alpha1
kind: GarageAdminToken
metadata:
  name: bootstrap-admin
spec:
  clusterRef:
    name: garage
  name: Bootstrap Admin Token
  neverExpires: true
  secretTemplate:
    name: garage-bootstrap-admin
    tokenKey: admin-token
    endpointKey: admin-endpoint
    includeEndpoint: true
