---
apiVersion: garage.rajsingh.info/v1beta1
kind: GarageCluster
metadata:
  name: garage
spec:
  replicas: 1
  # renovate: datasource=docker depName=dxflrs/garage
  image: dxflrs/garage:v2.3.0

  replication:
    factor: 1

  layoutManagement:
    autoApply: true
    minNodesHealthy: 1

  storage:
    metadata:
      size: 5Gi
      storageClassName: openebs-hostpath
    data:
      size: 50Gi
      storageClassName: openebs-hostpath
    pvcRetentionPolicy:
      whenDeleted: Retain
      whenScaled: Retain

  network:
    rpcBindPort: 3901
    service:
      type: ClusterIP

  s3Api:
    bindPort: 3900
    region: garage
    rootDomain: ".s3.siron.casa"

  monitoring:
    enabled: true
    interval: 30s
    additionalLabels:
      component: garage

  database:
    engine: lmdb

  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      memory: 1Gi
