---
apiVersion: garage.rajsingh.info/v1alpha1
kind: GarageKey
metadata:
  name: pulumi
spec:
  clusterRef:
    name: garage
  bucketPermissions:
    - bucketRef: statebucket
      bucketNamespace: garage
      read: true
      write: true
      owner: true
  neverExpires: true
