---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app penpot
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 1h
  path: ./k8s/apps/penpot/penpot/app
  components:
#    - ../../../../../k8s-components/volsync
    - ../../../../../k8s-components/dragonfly
    - ../../../../../k8s-components/cnpg/backup
  postBuild:
    substitute:
      APP: *app
      DRAGONFLY_REPLICAS: 1
      CNPG_VERSION: "16.11"
      CNPG_REPLICAS: "1"
#      CNPG_REQUESTS_CPU: 100m
      CNPG_LIMITS_MEMORY: 500m
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 5m
  wait: true
