---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: renovate-operator
spec:
  url: https://helm.mogenius.com/public
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: renovate-operator
spec:
  chart:
    spec:
      chart: renovate-operator
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: renovate-operator
  interval: 30m
  values:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
      dashboard:
        enabled: true
        grafanaDashboard:
          allowCrossNamespaceImport: true
          instanceSelector:
            matchLabels:
              grafana.internal/instance: ~
              instance: grafana
