---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: renovate-operator
spec:
  endpoints:
    - interval: 10s
      path: /metrics
      port: http
  selector:
    matchLabels:
      helm.toolkit.fluxcd.io/name: renovate-operator
  namespaceSelector:
    matchNames:
      - renovate