---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app authentik
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../../k8s-components/volsync
    - ../../../../../k8s-components/dragonfly
    - ../../../../../k8s-components/cnpg/backup
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: dragonfly
      namespace: database
    - name: cloudnative-pg
      namespace: database
  interval: 1h
  path: ./k8s/base/authentik/authentik/app
  postBuild:
    substitute:
      APP: *app
      # renovate: datasource=docker depName=ghcr.io/cloudnative-pg/postgresql
      CNPG_VERSION: "18.0"
      CNPG_SIZE: 10Gi
      CNPG_REQUESTS_CPU: 1Gi
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 5m
