---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: operator-oauth
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        key: tailscale-operator/client-id
    - secretKey: client_secret
      remoteRef:
        key: tailscale-operator/client-secret
