---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: booklore
components:
  - ../../components/common
resources:
  - ./booklore/ks.yaml
replacements:
  - path: ../../components/replacements/ks.yaml
