---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: papra
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: papra-secret
    template:
      data:
        AUTH_SECRET: "{{ .auth_secret }}"
        AUTH_PROVIDERS_EMAIL_IS_ENABLED: "false"
        AUTH_PROVIDERS_CUSTOMS: >-
          [{"providerId":"kanidm","providerName":"Kanidm","type":"oidc","clientId":"{{ .client_id }}","clientSecret":"{{ .client_secret }}","discoveryUrl":"https://sso.siron.casa/oauth2/openid/papra-app/.well-known/openid-configuration","scopes":["openid","profile","email"],"redirectURI":"https://papra.siron.casa/api/auth/oauth2/callback/kanidm","pkce":true}]
  data:
    - secretKey: auth_secret
      remoteRef:
        key: papra
        property: auth_secret
    - secretKey: client_id
      remoteRef:
        key: papra-kanidm-oidc
        property: client_id
    - secretKey: client_secret
      remoteRef:
        key: papra-kanidm-oidc
        property: client_secret