---
apiVersion: kaniop.rs/v1beta1
kind: KanidmOAuth2Client
metadata:
  name: papra-app
spec:
  displayname: Papra
  kanidmRef:
    name: sso
    namespace: sso
  origin: https://papra.siron.casa
  redirectUrl:
    - https://papra.siron.casa/api/auth/oauth2/callback/kanidm
  scopeMap:
    - group: papra
      scopes:
        - openid
        - profile
        - email
---
apiVersion: kaniop.rs/v1beta1
kind: KanidmGroup
metadata:
  name: papra
spec:
  kanidmRef:
    name: sso
    namespace: sso
  accountPolicy:
    authSessionExpiry: 2678400
  members:
    - sironheart