---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: papra-kanidm-oidc
spec:
  refreshInterval: 5m
  deletionPolicy: Delete
  updatePolicy: Replace
  secretStoreRefs:
    - name: onepassword
      kind: ClusterSecretStore
  selector:
    secret:
      name: papra-app-kanidm-oauth2-credentials
  data:
    - match:
        secretKey: CLIENT_ID
        remoteRef:
          remoteKey: papra-kanidm-oidc
          property: client_id
    - match:
        secretKey: CLIENT_SECRET
        remoteRef:
          remoteKey: papra-kanidm-oidc
          property: client_secret