---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network
resources:
  - ./envoy-gateway/ks.yaml
  - ./external-dns/ks.yaml
  - ./tailscale/ks.yaml
components:
  - ../../../k8s-components/common
replacements:
  - path: ../../../k8s-components/replacements/ks.yaml
