---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8tz
spec:
  chartRef:
    kind: OCIRepository
    name: k8tz
  interval: 30m
  values:
    namespace: system-controllers
    replicaCount: 1
    timezone: Europe/Berlin
    cronJobTimeZone: false
    webhook:
      ignoredNamespaces:
        - atuin
        - cert-manager
        - external-secrets
        - forgejo
        - garage
        - jellyfin
        - karakeep
        - kube-system
        - network
        - openebs
        - renovate
        - rook-ceph
        - system-upgrade
      certManager:
        enabled: true
        issuerRef:
          name: k8tz-webhook-issuer
          kind: Issuer
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: k8tz
              topologyKey: kubernetes.io/hostname
  postRenderers:
    - kustomize:
        patches:
          - target:
              version: v1
              kind: Namespace
            patch: |-
              $patch: delete
              apiVersion: v1
              kind: Namespace
              metadata:
                name: not-used
