---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-backups
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: db-backups
    template:
      data:
        AWS_ACCESS_KEY_ID: "{{ .access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ .secret_key }}"
  dataFrom:
    - extract:
        key: volsync-template
