---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: hetzner-s3
spec:
  retentionPolicy: "30d"
  configuration:
    endpointURL: https://nbg1.your-objectstorage.com
    destinationPath: s3://nbg1.your-objectstorage.com/cnpg-home-backup
    s3Credentials:
      accessKeyId:
        name: db-backups
        key: AWS_ACCESS_KEY_ID
      secretAccessKey:
        name: db-backups
        key: AWS_SECRET_ACCESS_KEY
