---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: pgadmin-default-password
spec:
  length: 32
  digits: 8
  symbols: 0
  noUpper: false
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgadmin
spec:
  refreshInterval: "0"
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: pgadmin-secret
    template:
      data:
        PGADMIN_DEFAULT_PASSWORD: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: pgadmin-default-password
