---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: rocm
spec:
  interval: 1h
  url: https://rocm.github.io/gpu-operator
  timeout: 3m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rocm
  namespace: system
spec:
  interval: 1h
  chart:
    spec:
      chart: gpu-operator-charts
      version: v1.4.1
      sourceRef:
        kind: HelmRepository
        name: rocm
  values:
    upgradePolicy:
      upgradeStrategy: OnDelete
    serviceMonitor:
      enabled: true
      attachMetadata:
        node: true
