---
apiVersion: kaniop.rs/v1beta1
kind: KanidmOAuth2Client
metadata:
  name: gotosocial-app
spec:
  displayname: GoToSocial
  image:
    url: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/gotosocial.svg
  kanidmRef:
    name: sso
    namespace: sso
  origin: https://gts.siron.casa
  redirectUrl:
    - https://gts.siron.casa/auth/callback
  public: false
  allowInsecureClientDisablePkce: true
  scopeMap:
    - group: gotosocial
      scopes:
        - openid
        - email
        - profile
        - groups
---
apiVersion: kaniop.rs/v1beta1
kind: KanidmGroup
metadata:
  name: gotosocial
spec:
  kanidmRef:
    name: sso
    namespace: sso
  accountPolicy:
    authSessionExpiry: 2678400
  members:
    - sironheart
