---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: continuwuity
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: continuwuity
    template:
      templateFrom:
        - configMap:
            name: continuwuity-config
            items:
              - key: continuwuity.toml
  dataFrom:
    - extract:
        key: continuwuity
