---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app karakeep
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/kopiur
    - ../../../../components/volsync
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 1h
  path: ./k8s/apps/karakeep/karakeep/app
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 10Gi
      VOLSYNC_ACCESSMODES: ReadWriteMany
      VOLSYNC_STORAGECLASS: ceph-filesystem
      VOLSYNC_SNAPSHOTCLASS: csi-ceph-filesystem
      KOPIUR_CAPACITY: 10Gi
      KOPIUR_ACCESSMODES: ReadWriteMany
      KOPIUR_STORAGECLASS: ceph-filesystem
      KOPIUR_SNAPSHOTCLASS: csi-ceph-filesystem
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 5m
  wait: false
