---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: system
resources:
  - ./amd-gpu/ks.yaml
  - ./descheduler/ks.yaml
  - ./kopia/ks.yaml
  - ./spegel/ks.yaml
  - ./volsync/ks.yaml
components:
  - ../../../k8s-components/common
