---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/externaldns.k8s.io/dnsendpoint_v1alpha1.json
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: external
spec:
  endpoints:
    - dnsName: cftunnel.siron.casa
      recordType: CNAME
      targets: ["f62608ff-165c-47ed-9327-5f273a8af9f6.cfargotunnel.com"]
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: "true"
