---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-oauth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: auth-generic-oauth-secret
    template:
      data:
        AUTH_CLIENT_ID: "{{ .client_id }}"
        AUTH_CLIENT_SECRET: "{{ .client_secret }}"
  dataFrom:
    - extract:
        key: grafana-oauth
