---
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    instance: grafana
spec:
  # renovate: datasource=github-releases depName=grafana/grafana
  version: 13.0.1
  config:
    analytics:
      check_for_updates: "false"
      check_for_plugin_updates: "false"
      feedback_links_enabled: "false"
      reporting_enabled: "false"
    auth:
      disable_login_form: "false"
    auth.anonymous:
      enabled: "false"
    auth.generic_oauth:
      name: kanidm
      enabled: "true"
      auto_login: "true"
      client_id: ${CLIENT_ID}
      client_secret: ${CLIENT_SECRET}
      scopes: "openid profile email groups"
      email_attribute_path: email
      use_pkce: "true"
      use_refresh_token: "true"
      login_attribute_path: preferred_username
      groups_attribute_path: groups
      allow_assign_grafana_admin: "true"
      auth_url: "https://sso.siron.casa/ui/oauth2"
      token_url: "https://sso.siron.casa/oauth2/token"
      api_url: "https://sso.siron.casa/oauth2/openid/grafana/userinfo"
      role_attribute_path: "contains(grafana_role[*], 'GrafanaAdmin') && 'GrafanaAdmin' || contains(grafana_role[*], 'Admin') && 'Admin' || contains(grafana_role[*], 'Editor') && 'Editor' || 'Viewer'"
    log:
      mode: console
    log.console:
      format: json
    metrics:
      enabled: "true"
    news:
      news_feed_enabled: "false"
    plugins:
      plugin_admin_enabled: "false"
    security:
      angular_support_enabled: "false"
    server:
      enable_gzip: "true"
      root_url: https://grafana.siron.casa
  httpRoute:
    spec:
      hostnames:
        - grafana.siron.casa
      parentRefs:
        - name: external
          namespace: network
  persistentVolumeClaim:
    spec:
      storageClassName: ceph-block
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
  deployment:
    metadata:
      annotations:
        reloader.stakater.com/auto: "true"
    spec:
      strategy:
        type: Recreate
      template:
        spec:
          containers:
            - name: grafana
              envFrom:
                - secretRef:
                    name: grafana-app-kanidm-oauth2-credentials
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                capabilities: { drop: ["ALL"] }
              resources:
                requests:
                  cpu: 160m
                  memory: 363Mi
                limits:
                  memory: 363Mi
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
  disableDefaultSecurityContext: All
