---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: dragonfly-${APP}
spec:
  selector:
    matchLabels:
      app: dragonfly-${APP}
  podTargetLabels: ["app"]
  podMetricsEndpoints:
    - port: admin
  fallbackScrapeProtocol: PrometheusText0.0.4
