---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: konflate
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: konflate-secret
    template:
      engineVersion: v2
      data:
        KONFLATE_TOKEN: "{{ .token }}"
        KONFLATE_WEBHOOK_SECRET: "{{ .webhookSecret }}"
        KONFLATE_WRITE_TOKEN: "{{ .writeToken }}"
  dataFrom:
    - extract:
        key: konflate
