---
rollOutCiliumPods: true
policyAuditMode: true
logOptions:
  format: json
# enableIPv4BIGTCP: true

ipv4:
  enabled: true
ipv6:
  enabled: true
enableIPv6Masquerade: true

l2announcements:
  enabled: true

localRedirectPolicies:
  enabled: true

endpointRoutes:
  enabled: true

nodeIPAM:
  enabled: true

operator:
  replicas: 1
  rollOutPods: true
  dashboards:
    enabled: true
  metrics:
    enabled: true
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true

cni:
  exclusive: false

prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
    trustCRDsExist: true

envoy:
  prometheus:
    serviceMonitor:
      enabled: true

dashboards:
  enabled: true

hubble:
  enabled: false
  tls:
    auto:
      method: certmanager
      certManagerIssuerRef:
        group: cert-manager.io
        kind: Issuer
        name: hubble-ca
  ui:
    enabled: false
  relay:
    enabled: false

# -- from talos docs --
ipam:
  mode: kubernetes

kubeProxyReplacement: true
k8sServiceHost: 127.0.0.1
k8sServicePort: 7445
kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256

securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE

cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup
# -- end of talos settings --

# -- required for tailscale --
socketLB:
  hostNamespaceOnly: true
# -- end of tailscale settings --
