---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: siron-casa
spec:
  secretName: siron-casa-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: siron.casa
  dnsNames: ["siron.casa", "*.siron.casa"]
