---
clusterName: home
# renovate: depName=ghcr.io/siderolabs/installer datasource=docker
talosVersion: 1.10.6
# renovate: depName=ghcr.io/siderolabs/kubelet datasource=docker
kubernetesVersion: v1.33.4

endpoint: https://talos.home:6443
allowSchedulingOnMasters: true
cniConfig:
  name: none

additionalMachineCertSans: &san
  - 127.0.0.1 #KubePrism
  - 192.168.0.11 #Talos01
  - 192.168.0.12 #Talos02
  - 192.168.0.13 #Talos03
  - talos.home #DNS route to cluster
additionalApiServerCertSans: *san

nodes:
  - hostname: talos01
    ipAddress: 192.168.0.11
    controlPlane: true
    disableSearchDomain: true

    installDisk: "/dev/nvme0n1"

    machineSpec:
      mode: metal
      arch: amd64
      secureboot: false
      useUKI: false

    networkInterfaces: &network
      - deviceSelector:
          physical: true
        dhcp: true


  - hostname: talos02
    ipAddress: 192.168.0.12
    controlPlane: true
    disableSearchDomain: true

    installDisk: "/dev/nvme0n1"

    machineSpec:
      mode: metal
      arch: amd64
      secureboot: false
      useUKI: false

    networkInterfaces: *network

  - hostname: talos03
    ipAddress: 192.168.0.13
    controlPlane: true
    disableSearchDomain: true

    installDisk: "/dev/nvme0n1"

    machineSpec:
      mode: metal
      arch: amd64
      secureboot: false
      useUKI: false

    networkInterfaces: *network

controlPlane:
  schematic:
    customization:
      systemExtensions:
        officialExtensions:
        - siderolabs/amdgpu
        - siderolabs/iscsi-tools
        - siderolabs/util-linux-tools

patches:
  - |-
    machine:
      install:
        extraKernelArgs:
          - amd_pstate=active
  # Disable search domain everywhere
  - |-
    machine:
      network:
        disableSearchDomain: true

  # Enable host dns
  - |-
    machine:
      features:
        hostDNS:
          enabled: true
          resolveMemberNames: true
          forwardKubeDNSToHost: false

  # Kubelet mount and machine labels for longhorn
  - |-
    machine:
      nodeLabels:
        node.longhorn.io/create-default-disk: config
      nodeAnnotations:
        node.longhorn.io/default-disks-config: '[{"path":"/var/lib/longhorn","allowScheduling":true}]'
      kubelet:
        extraMounts:
          - destination: /var/lib/longhorn
            type: bind
            source: /var/lib/longhorn
            options: [bind, rshared, rw]

  # Wipe disk on install
  - |-
    machine:
      install:
        wipe: true

  # Replace kubeproxy with cilium
  - |-
    cluster:
      proxy:
        disabled: true

  # Kubelet configuration
  - |-
    machine:
      kubelet:
        disableManifestsDirectory: true
        extraConfig:
          maxPods: 250

  # Configure cluster
  - |-
    cluster:
      allowSchedulingOnControlPlanes: true
      controllerManager:
        extraArgs:
          bind-address: 0.0.0.0
      coreDNS:
          disabled: true
      proxy:
        disabled: true
      scheduler:
        config:
          apiVersion: kubescheduler.config.k8s.io/v1
          kind: KubeSchedulerConfiguration
          profiles:
            - schedulerName: default-scheduler
              pluginConfig:
                - name: PodTopologySpread
                  args:
                    defaultingType: List
                    defaultConstraints:
                      - maxSkew: 1
                        topologyKey: kubernetes.io/hostname
                        whenUnsatisfiable: ScheduleAnyway

  # Longhorn settings
  - |-
    cluster:
      apiServer:
        admissionControl:
        - name: PodSecurity
          configuration:
            apiVersion: pod-security.admission.config.k8s.io/v1alpha1
            kind: PodSecurityConfiguration
            defaults:
              audit: restricted
              audit-version: latest
              enforce: baseline
              enforce-version: latest
              warn: restricted
              warn-version: latest
            exemptions:
              namespaces:
                # - kube-system
                - longhorn-system
                - metallb-system
                - observability
                - network
              runtimeClasses: []
              usernames: []
        auditPolicy:
          apiVersion: audit.k8s.io/v1
          kind: Policy
          rules:
            - level: Metadata

  # Etcd metrics
  - |-
    cluster:
      etcd:
        extraArgs:
          listen-metrics-urls: http://0.0.0.0:2381

  # Enable K8s Talos API Access
  - |-
    machine:
      features:
        kubernetesTalosAPIAccess:
          enabled: true
          allowedRoles:
            - os:admin
          allowedKubernetesNamespaces:
            - actions-runner-system
            - system-upgrade
