---
clusterName: home
# renovate: depName=ghcr.io/siderolabs/installer datasource=docker
talosVersion: v1.12.0
# renovate: depName=ghcr.io/siderolabs/kubelet datasource=docker
kubernetesVersion: v1.35.0

endpoint: https://internal.siron.casa:6443
allowSchedulingOnMasters: true
cniConfig:
  name: none

additionalMachineCertSans: &san
  - 127.0.0.1 #KubePrism
  - 192.168.0.11 #Talos01
  - 192.168.0.12 #Talos02
  - 192.168.0.13 #Talos03
  - internal.siron.casa #DNS route to cluster
additionalApiServerCertSans: *san

controlPlane:
  schematic:
    customization:
      systemExtensions:
        officialExtensions:
          - siderolabs/amdgpu

nodes:
  - hostname: talos01
    ipAddress: 192.168.0.11
    controlPlane: true
    disableSearchDomain: true

    installDiskSelector: &diskSelector
      model: CT1000P3PSSD8

    machineSpec: &machinespec
      mode: metal
      arch: amd64
      secureboot: false
      useUKI: false

    networkInterfaces: &network
      - deviceSelector:
          physical: true
        dhcp: true

    nodeLabels: &labels
      feature.node.kubernetes.io/amd-gpu: "true"

    userVolumes: &userVolumes
      - name: local-hostpath
        provisioning:
          diskSelector:
            match: system_disk
          minSize: 128GiB
        filesystem:
          type: xfs

    volumes: &volumes
      - name: EPHEMERAL
        provisioning:
          diskSelector:
            match: system_disk
          minSize: 200GiB
          maxSize: 400GiB
          grow: false

  - hostname: talos02
    ipAddress: 192.168.0.12
    controlPlane: true
    disableSearchDomain: true

    installDiskSelector: *diskSelector

    machineSpec: *machinespec

    networkInterfaces: *network

    nodeLabels: *labels

    userVolumes: *userVolumes
    volumes: *volumes

  - hostname: talos03
    ipAddress: 192.168.0.13
    controlPlane: true
    disableSearchDomain: true

    installDiskSelector: *diskSelector

    machineSpec: *machinespec

    networkInterfaces: *network

    nodeLabels: *labels

    userVolumes: *userVolumes
    volumes: *volumes

patches:
  # Enable host dns
  - |-
    machine:
      features:
        apidCheckExtKeyUsage: true
        diskQuotaSupport: true
        hostDNS:
          enabled: true
          resolveMemberNames: true
          forwardKubeDNSToHost: false

  # Wipe disk on install
  - |-
    machine:
      install:
        wipe: true

  # Replace kubeproxy with cilium
  - |-
    cluster:
      proxy:
        disabled: true

  # Kubelet configuration
  - |-
    machine:
      kubelet:
        disableManifestsDirectory: true
        extraConfig:
          maxPods: 250
          serializeImagePulls: false

  # NFS settings
  - |-
    machine:
      files:
      - op: create
        path: /etc/cri/conf.d/20-customization.part
        content: |-
          [plugins]
          [plugins."io.containerd.grpc.v1.cri"]
            enable_unprivileged_ports = true
            enable_unprivileged_icmp = true
          [plugins."io.containerd.cri.v1.images"]
            discard_unpacked_layers = false
          [plugins."io.containerd.cri.v1.runtime"]
            cdi_spec_dirs = ["/var/cdi/static", "/var/cdi/dynamic"]
            device_ownership_from_security_context = true
      - op: overwrite
        path: /etc/nfsmount.conf
        permissions: 0o644
        content: |
          [ NFSMount_Global_Options ]
          nfsvers=4.1
          hard=True
          noatime=True
          nconnect=16

  # Configure cluster
  - |-
    cluster:
      apiServer:
        extraArgs:
          enable-aggregator-routing: "true"
          feature-gates: MutatingAdmissionPolicy=true
          runtime-config: admissionregistration.k8s.io/v1beta1=true
        disablePodSecurityPolicy: true
      controllerManager:
        extraArgs:
          bind-address: 0.0.0.0
      coreDNS:
          disabled: true
      proxy:
        disabled: true
      scheduler:
          config:
            apiVersion: kubescheduler.config.k8s.io/v1
            kind: KubeSchedulerConfiguration
            profiles:
              - pluginConfig:
                  - args:
                      defaultConstraints:
                        - maxSkew: 1
                          topologyKey: kubernetes.io/hostname
                          whenUnsatisfiable: ScheduleAnyway
                      defaultingType: List
                    name: PodTopologySpread
                plugins:
                  score:
                    disabled:
                      - name: ImageLocality
                schedulerName: default-scheduler

  # Etcd metrics
  - |-
    cluster:
      etcd:
        extraArgs:
          listen-metrics-urls: http://0.0.0.0:2381

  # Enable K8s Talos API Access
  - |-
    machine:
      features:
        kubernetesTalosAPIAccess:
          enabled: true
          allowedRoles:
            - os:admin
          allowedKubernetesNamespaces:
            - actions-runner-system
            - system-upgrade

  - |-
    cluster:
      apiServer:
        disablePodSecurityPolicy: true
        admissionControl:
        - name: PodSecurity
          configuration:
            exemptions:
              namespaces:
                - network
                - observability
                - openebs
                - rook-ceph
                - system
  - |-
    apiVersion: v1alpha1
    kind: OOMConfig
    triggerExpression: "false"
