---
clusterName: home
# renovate: depName=ghcr.io/siderolabs/installer datasource=docker
talosVersion: v1.11.2
# renovate: depName=ghcr.io/siderolabs/kubelet datasource=docker
kubernetesVersion: v1.34.1

endpoint: https://internal.siron.casa:6443
allowSchedulingOnMasters: true
cniConfig:
  name: none

additionalMachineCertSans: &san
  - 127.0.0.1 #KubePrism
  - 192.168.0.11 #Talos01
  - 192.168.0.12 #Talos02
  - 192.168.0.13 #Talos03
  - internal.siron.casa #DNS route to cluster
additionalApiServerCertSans: *san

controlPlane:
  schematic:
    customization:
      systemExtensions:
        officialExtensions:
          - siderolabs/amdgpu
          - siderolabs/iscsi-tools
          - siderolabs/util-linux-tools

nodes:
  - hostname: talos01
    ipAddress: 192.168.0.11
    controlPlane: true
    disableSearchDomain: true

    installDiskSelector: &diskSelector
      model: CT1000P3PSSD8

    machineSpec: &machinespec
      mode: metal
      arch: amd64
      secureboot: false
      useUKI: false

    networkInterfaces: &network
      - deviceSelector:
          physical: true
        dhcp: true

    nodeLabels: &labels
      node.longhorn.io/create-default-disk: config
      feature.node.kubernetes.io/amd-gpu: "true"

    nodeAnnotations: &annotations
      node.longhorn.io/default-disks-config: '[{"path":"/var/mnt/longhorn","allowScheduling":true}]'

    userVolumes: &userVolumes
      - name: longhorn
        provisioning:
          diskSelector: &defaultDiskSelector
            match: system_disk
          minSize: 128GiB
          maxSize: 200GiB
        filesystem:
          type: xfs
      - name: local-hostpath
        provisioning:
          diskSelector: *defaultDiskSelector
          minSize: 128GiB
          maxSize: 384GiB
        filesystem:
          type: xfs

    volumes: &volumes
      - name: EPHEMERAL
        provisioning:
          diskSelector:
            match: system_disk
          minSize: 200GiB
          maxSize: 400GiB
          grow: false

  - hostname: talos02
    ipAddress: 192.168.0.12
    controlPlane: true
    disableSearchDomain: true

    installDiskSelector: *diskSelector

    machineSpec: *machinespec

    networkInterfaces: *network

    nodeLabels: *labels
    nodeAnnotations: *annotations

    userVolumes: *userVolumes
    volumes: *volumes

  - hostname: talos03
    ipAddress: 192.168.0.13
    controlPlane: true
    disableSearchDomain: true

    installDiskSelector: *diskSelector

    machineSpec: *machinespec

    networkInterfaces: *network

    nodeLabels: *labels
    nodeAnnotations: *annotations

    userVolumes: *userVolumes
    volumes: *volumes

patches:
  # Enable host dns
  - |-
    machine:
      features:
        apidCheckExtKeyUsage: true
        diskQuotaSupport: true
        hostDNS:
          enabled: true
          resolveMemberNames: true
          forwardKubeDNSToHost: false

  # Wipe disk on install
  - |-
    machine:
      install:
        wipe: true

  # Replace kubeproxy with cilium
  - |-
    cluster:
      proxy:
        disabled: true

  # Kubelet configuration
  - |-
    machine:
      kubelet:
        disableManifestsDirectory: true
        extraConfig:
          maxPods: 250

  # Configure cluster
  - |-
    cluster:
      allowSchedulingOnControlPlanes: true
      controllerManager:
        extraArgs:
          bind-address: 0.0.0.0
      coreDNS:
          disabled: true
      proxy:
        disabled: true

  # Longhorn settings
  - |-
    cluster:
      apiServer:
        disablePodSecurityPolicy: true
        admissionControl:
        - name: PodSecurity
          configuration:
            apiVersion: pod-security.admission.config.k8s.io/v1alpha1
            kind: PodSecurityConfiguration
            defaults:
              audit: restricted
              audit-version: latest
              enforce: baseline
              enforce-version: latest
              warn: restricted
              warn-version: latest
            exemptions:
              namespaces:
                - longhorn-system
                - network
                - observability
                - openebs
                - volsync-system
              runtimeClasses: []
              usernames: []
        auditPolicy:
          apiVersion: audit.k8s.io/v1
          kind: Policy
          rules:
            - level: Metadata

  # Etcd metrics
  - |-
    cluster:
      etcd:
        extraArgs:
          listen-metrics-urls: http://0.0.0.0:2381

  # Enable K8s Talos API Access
  - |-
    machine:
      features:
        kubernetesTalosAPIAccess:
          enabled: true
          allowedRoles:
            - os:admin
          allowedKubernetesNamespaces:
            - actions-runner-system
            - system-upgrade
