---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-runner
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: forgejo-runner-secret
    template:
      data:
        RUNNER_UUID: "{{ .forgejo_runner_uuid }}"
        RUNNER_TOKEN: "{{ .forgejo_runner_token }}"
  dataFrom:
    - extract:
        key: forgejo-runner
