---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: unpoller
components:
  - ../../components/common
resources:
  - ./unpoller/ks.yaml
replacements:
  - path:  ../../components/replacements/ks.yaml
