---
apiVersion: kaniop.rs/v1beta1
kind: KanidmOAuth2Client
metadata:
  name: forgejo-app
spec:
  displayname: Forgejo
  image:
    url: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/forgejo.svg
  kanidmRef:
    name: sso
    namespace: sso
  origin: https://forgejo.siron.casa/
  redirectUrl:
    - https://forgejo.siron.casa/user/oauth2/kanidm/callback
  scopeMap:
    - group: forgejo
      scopes:
        - openid
        - profile
        - email
        - groups
---
apiVersion: kaniop.rs/v1beta1
kind: KanidmGroup
metadata:
  name: forgejo
spec:
  kanidmRef:
    name: sso
    namespace: sso
  accountPolicy:
    authSessionExpiry: 2678400
  members:
    - sironheart
