---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: forgejo-kanidm-oidc
spec:
  refreshInterval: 5m
  updatePolicy: Replace
  secretStoreRefs:
    - name: onepassword
      kind: ClusterSecretStore
  selector:
    secret:
      name: forgejo-app-kanidm-oauth2-credentials
  data:
    - match:
        secretKey: CLIENT_ID
        remoteRef:
          remoteKey: forgejo-kanidm-oidc
          property: key
    - match:
        secretKey: CLIENT_SECRET
        remoteRef:
          remoteKey: forgejo-kanidm-oidc
          property: secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-kanidm-oidc
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: forgejo-kanidm-oidc
  data:
    - secretKey: key
      remoteRef:
        key: forgejo-kanidm-oidc
        property: key
    - secretKey: secret
      remoteRef:
        key: forgejo-kanidm-oidc
        property: secret
