---
apiVersion: kaniop.rs/v1beta1
kind: KanidmOAuth2Client
metadata:
  name: teamcity-app
spec:
  displayname: TeamCity
  image:
    url: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/teamcity.svg
  kanidmRef:
    name: sso
    namespace: sso
  origin: https://teamcity.siron.casa/
  redirectUrl:
    - https://teamcity.siron.casa/app/login
  preferShortUsername: true
  allowInsecureClientDisablePkce: true
  scopeMap:
    - group: teamcity
      scopes:
        - openid
        - profile
        - email
        - groups
---
apiVersion: kaniop.rs/v1beta1
kind: KanidmGroup
metadata:
  name: teamcity
spec:
  kanidmRef:
    name: sso
    namespace: sso
  accountPolicy:
    authSessionExpiry: 2678400
  members:
    - sironheart
