---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-discord-webhook
spec:
  refreshInterval: 30m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: alertmanager-discord-webhook
    template:
      data:
        webhook-url: "{{ .webhook_url }}"
  dataFrom:
    - extract:
        key: alertmanager-discord-webhook
