---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/grafana.integreatly.org/grafanadatasource_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: victoriametrics
spec:
  allowCrossNamespaceImport: true
  instanceSelector:
    matchLabels:
      instance: grafana
  datasource:
    access: proxy
    type: victoriametrics-metrics-datasource
    name: VictoriaMetrics
    url: http://vmsingle-vm:8428
  resyncPeriod: "10m0s"
  plugins:
    - name: victoriametrics-metrics-datasource
      version: 0.19.5
