---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vm-agent
spec:
  extraArgs:
    enableTCP6: "true"
  scrapeInterval: 20s
  selectAllByDefault: true
  remoteWrite:
    - url: 'http://vmsingle-vm.observability.svc:8428/api/v1/write'
