---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: vm
spec:
  image:
    repository: victoriametrics/victoria-metrics
    tag: v1.139.0
    pullPolicy: IfNotPresent
  extraArgs:
    enableTCP6: "true"
  retentionPeriod: 365d
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        cpu: 41m
        memory: 1622Mi
        storage: 50Gi
      limits:
        cpu: ~
        memory: 1622Mi
