---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: vm
spec:
  image:
    repository: victoriametrics/victoria-metrics
    tag: v1.134.0
    pullPolicy: IfNotPresent
  extraArgs:
    enableTCP6: "true"
  retentionPeriod: 365d
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 50Gi
