---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: vm
spec:
  retentionPeriod: 30d
  extraArgs:
    dedup.minScrapeInterval: 60s
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 50Gi
