---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: flux-instance
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: github-webhook-token
    template:
      data:
        token: "{{ .token }}"
  dataFrom:
    - extract:
        key: Github
