---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app teamcity
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/volsync
    - ../../../../components/database
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: cloudnative-pg
      namespace: database
  interval: 1h
  path: ./k8s/apps/teamcity/teamcity/app
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 20Gi
      DATABASE_KEY_ALGORITHM: RSA
      DATABASE_KEY_SIZE: '"4096"'
      DATABASE_KEY_ENCODING: PKCS8
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 5m
  wait: false
