---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: booklore
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: booklore-secret
    template:
      data:
        DATABASE_URL: jdbc:mariadb://localhost:3306/booklore
        DATABASE_USERNAME: booklore
        DATABASE_PASSWORD: "{{ .db_password }}"
        DATABASE_ROOT_PASSWORD: "{{ .db_root_password }}"
  dataFrom:
    - extract:
        key: booklore
