---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app booklore
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: default
  values:
    controllers:
      booklore:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          booklore:
            image:
              repository: ghcr.io/booklore-app/booklore
              tag: v2.0.1@sha256:e5c51133c0c50e97004bf711a34521c698e4b27b6847e54fe304c08ff4aa8ee1
            env:
              USER_ID: "1000"
              GROUP_ID: "1000"
              BOOKLORE_PORT: &port 6060
              SWAGGER_ENABLED: "false"
              LOGGING_STRUCTURED_FORMAT_CONSOLE: logstash
            envFrom:
              - secretRef:
                  name: booklore-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  initialDelaySeconds: 30
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 10m
                memory: 1Gi
              limits:
                memory: 4Gi
          mariadb:
            image:
              repository: lscr.io/linuxserver/mariadb
              tag: 11.4.8
            env:
              MYSQL_USER: booklore
              MYSQL_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: booklore-secret
                    key: DATABASE_PASSWORD
              MYSQL_DATABASE: booklore
              MYSQL_ROOT_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: booklore-secret
                    key: DATABASE_ROOT_PASSWORD
    service:
      booklore:
        controller: *app
        ports:
          http:
            port: *port
    route:
      booklore:
        hostnames: ["books.siron.casa"]
        parentRefs:
          - name: internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port
            timeouts:
              request: 0s
    persistence:
      data:
        enabled: true
        existingClaim: *app
        advancedMounts:
          booklore:
            booklore:
              - path: /app/data
                subPath: app
            mariadb:
              - path: /config
                subPath: db
      library:
        type: nfs
        server: 192.168.0.2
        path: /volume2/shows/books
        advancedMounts:
          booklore:
            booklore:
              - path: /books
      bookdrop:
        type: nfs
        server: 192.168.0.2
        path: /volume2/shows/bookdrop
        advancedMounts:
          booklore:
            booklore:
              - path: /bookdrop
