---
apiVersion: kaniop.rs/v1beta1
kind: KanidmOAuth2Client
metadata:
  name: booklore-app
spec:
  displayname: Booklore
  kanidmRef:
    name: sso
    namespace: sso
  origin: https://books.siron.casa/
  redirectUrl:
    - https://books.siron.casa/oauth2-callback
  strictRedirectUrl: false
  public: true
  preferShortUsername: true
  scopeMap:
    - group: booklore
      scopes:
        - openid
        - profile
        - email
        - offline_access
---
apiVersion: kaniop.rs/v1beta1
kind: KanidmGroup
metadata:
  name: booklore
spec:
  kanidmRef:
    name: sso
    namespace: sso
  members:
    - sironheart
