---
apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-postgres
stringData:
  url: "postgresql://${DATABASE_OWNER:=${APP}}@pooler-rw.database.svc:5432/${APP}?sslmode=verify-full&sslcert=/var/run/secrets/postgresql/tls.crt&sslkey=/var/run/secrets/postgresql/tls.key&sslrootcert=/var/run/secrets/root-ca/ca.crt"
  host: pooler-rw.database.svc
  port: "5432"
  user: "${DATABASE_OWNER:=${APP}}"
  db_name: "${APP}"
  ssl_ca: "/var/run/secrets/root-ca/ca.crt"
  ssl_key: "/var/run/secrets/postgresql/tls.key"
  ssl_cert: "/var/run/secrets/postgresql/tls.crt"
