---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - ./namespace.yaml
patches:
#  - target:
#      kind: HelmRelease
#      group: helm.toolkit.fluxcd.io
#      version: v2
#    patch: |-
#      - op: add
#        path: /spec/interval
#        value: 1h
#      - op: add
#        path: /spec/install
#        value:
#          crds: CreateReplace
#          remediation:
#            retries: -1
#      - op: add
#        path: /spec/uninstall
#        value:
#          keepHistory: false
#      - op: add
#        path: /spec/upgrade
#        value:
#          cleanupOnFail: true
#          crds: CreateReplace
#          remediation:
#            retries: 3
  - target:
      kind: Kustomization
      group: kustomize.toolkit.fluxcd.io
      version: v1
    patch: |-
      - op: add
        path: /spec/components/-
        value: ../../../../components/helmrelease-defaults
