apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
data:
  config.js: |
    module.exports = {
      platform: 'github',
      requireConfig: 'optional',
      onboardingConfigFileName: 'renovate.json5',
    };
