---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sironheart-renovate
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: sironheart-renovate
    template:
      data:
        RENOVATE_GITHUB_COM_USER: "{{ .githubUserSironheart }}"
        RENOVATE_GITHUB_COM_TOKEN: "{{ .githubTokenSironheart }}"
        RENOVATE_TOKEN: "{{ .githubTokenSironheart }}"
        webhook: "{{ .webhook }}"
  dataFrom:
    - extract:
        key: renovate
    - extract:
        key: renovate-webhook
