---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-token
spec:
  refreshInterval: 30m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: forgejo-renovate
    template:
      type: Opaque
      engineVersion: v2
      data:
        RENOVATE_TOKEN: "{{ .renovateToken }}"
        RENOVATE_GITHUB_COM_TOKEN: "{{ .token }}"
        RENOVATE_GITHUB_COM_USER: "Siron-Bot"
  dataFrom:
    - extract:
        key: forgejo-renovate
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: GithubAccessToken
          name: github-auth-token
