---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-webhook
spec:
  refreshInterval: 30m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: renovate-webhook
    template:
      data:
        webhook: "{{ .webhook }}"
  dataFrom:
    - extract:
        key: renovate-webhook

