---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-app-pem
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: siron-bot
  data:
    - secretKey: private_key_pem
      remoteRef:
        key: siron-bot
        property: private key
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: GithubAccessToken
metadata:
  name: github-auth-token
spec:
  appID: "1727690"
  installID: "79214846"
  auth:
    privateKey:
      secretRef:
        name: siron-bot
        key: private_key_pem
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-auth-token
spec:
  refreshInterval: 30m
  target:
    name: renovate-secret
    template:
      type: Opaque
      engineVersion: v2
      data:
        GITHUB_COM_TOKEN: "{{ .token }}"
        GITHUB_COM_USER: Siron-Bot
        RENOVATE_TOKEN: "{{ .token }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: GithubAccessToken
          name: github-auth-token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-webhook
spec:
  refreshInterval: 30m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: renovate-webhook
    template:
      data:
        webhook: "{{ .webhook }}"
  dataFrom:
    - extract:
        key: renovate-webhook
