---
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: forgejo-sironheart
spec:
  metadata:
    annotations:
      reloader.stakater.com/auto: "true"
  discoveryFilters:
    - sironheart/*
  discoverTopics: [renovate]
  # renovate: datasource=docker depName=renovate/renovate
  image: renovate/renovate:44.24.3
  parallelism: 2
  schedule: H H/4 * * *
  secretRef: forgejo-renovate
  extraEnv:
    # Admin-only option: allows Renovate to run mise (mise lock), bazel mod deps, go generate, and gradlew during updates.
    - name: RENOVATE_ALLOWED_UNSAFE_EXECUTIONS
      value: '["bazelModDeps", "goGenerate", "gradleWrapper", "mise"]'
    - name: RENOVATE_EXTENDS
      value: '["local>sironheart/renovate-preset"]'
    - name: RENOVATE_ONBOARDING_CONFIG_FILE_NAME
      value: renovate.json5
    # - name: RENOVATE_REBASE_WHEN
    #   value: behind-base-branch
    - name: RENOVATE_AUTOMERGE_STRATEGY
      value: fast-forward
  provider:
    name: forgejo
    endpoint: https://forgejo.siron.casa/api/v1
  webhook:
    enabled: true
    authentication:
      enabled: true
      secretRef:
        name: renovate-webhook
        key: webhook
