---
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: sironheart
spec:
  metadata:
    annotations:
      reloader.stakater.com/auto: "true"
  discoveryFilter: "sironheart/*"
  # renovate: datasource=docker depName=renovate/renovate
  image: renovate/renovate:43.4.2
  parallelism: 5
  schedule: 0 * * * *
  secretRef: sironheart-renovate
  extraVolumes:
    - name: renovate-config
      configMap:
        name: renovate-config
  extraVolumeMounts:
    - name: renovate-config
      mountPath: /config
  extraEnv:
    - name: RENOVATE_ENDPOINT
      value: https://api.github.com/
    - name: RENOVATE_ALLOW_PLUGINS
      value: "true"
    - name: RENOVATE_CONFIG_FILE
      value: /config/config.js
