---
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: sironheart
spec:
  metadata:
    annotations:
      reloader.stakater.com/auto: "true"
  discoveryFilter: "sironheart/*"
  # renovate: datasource=docker depName=renovate/renovate
  image: renovate/renovate:43.73.1
  parallelism: 2
  schedule: 0 * * * *
  secretRef: sironheart-renovate
  extraEnv:
    - name: RENOVATE_ALLOW_PLUGINS
      value: "true"
    - name: RENOVATE_ONBOARDING_CONFIG_FILE_NAME
      value: "renovate.json5"
  resources:
    requests:
      memory: 3Gi
      cpu: 1
    limits:
      memory: 3Gi
  provider:
    name: github
    endpoint: https://api.github.com/
