---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openebs
components:
  - ../../../k8s-components/common
resources:
  - ./openebs/ks.yaml
replacements:
  - path: ../../../k8s-components/replacements/ks.yaml
