---
# technically we only need one of these per namespace...
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: ${APP}-db
spec:
  retentionPolicy: 14d
  configuration:
    wal:
      compression: bzip2
      maxParallel: 8
    data:
      compression: bzip2
    destinationPath: s3://cnpg-home-backups
    endpointURL: https://nbg1.your-objectstorage.com
    s3Credentials:
      accessKeyId:
        name: &secret ${APP}-cnpg-secret
        key: AWS_ACCESS_KEY_ID
      secretAccessKey:
        name: *secret
        key: AWS_SECRET_ACCESS_KEY
