---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unifi-dns
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: unifi-dns-secret
    template:
      data:
        token: "{{ .token }}"
  dataFrom:
    - extract:
        key: unifi
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-dns
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cloudflare-dns-secret
    template:
      data:
        CF_API_TOKEN: "{{ .api_token }}"
        CF_ZONE_ID: "{{ .zone_id }}"
  dataFrom:
    - extract:
        key: cloudflare-dns
