---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: penpot
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: penpot
    template:
      data:
        PENPOT_OIDC_CLIENT_ID: "{{ .clientId }}"
        PENPOT_OIDC_CLIENT_SECRET: "{{ .clientSecret }}"
        PENPOT_SECRET_KEY: "{{ .appSecretKey }}"
  dataFrom:
    - extract:
        key: penpot-oauth
    - extract:
        key: penpot