---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: penpot
spec:
  interval: 1h
  url: http://helm.penpot.app
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: penpot
spec:
  interval: 1h
  chart:
    spec:
      chart: penpot
      sourceRef:
        kind: HelmRepository
        name: penpot
      version: 0.32.0
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  install:
    remediation:
      retries: -1
  values:
    config:
      publicUri: "https://penpot.siron.casa"
      telemetryEnabled: false
      existingSecret: penpot
      secretKeys:
        apiSecretKey: PENPOT_SECRET_KEY
      flags: "enable-oidc-registration enable-login-with-oidc disable-email-verification disable-login-with-password"
      fileDataBackend: "db"

      postgresql:
        username: penpot
        password: ""
        existingSecret: "penpot"
        secretKeys:
          postgresqlUriKey: "connection_url"

      redis:
        host: dragonfly-penpot.penpot.svc.cluster.local

      objectStorage:
        storageBackend: "fs"

      providers:
        oidc:
          enabled: true
          baseURI: "https://sso.siron.casa/oauth2/openid/penpot-app/"
          roles: ""
          rolesAttribute: ""
          scopes: "openid profile email"
          nameAttribute: nickname
          emailAttribute: email
        existingSecret: "penpot-app-kanidm-oauth2-credentials"
        secretKeys:
          oidcClientIDKey: CLIENT_ID
          oidcClientSecretKey: CLIENT_SECRET

    backend:
      volumes:
        - name: penpot-postgres
          secret:
            secretName: postgres-penpot-cert
            defaultMode: 440
        - name: root-ca
          secret:
            secretName: root-ca
            defaultMode: 440
      volumeMounts:
        - name: penpot-postgres
          mountPath: "/var/run/secrets/postgresql"
          readOnly: true
        - name: root-ca
          mountPath: "/var/run/secrets/root-ca"
          readOnly: true
    persistence:
      assets:
        existingClaim: penpot

