---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: penpot
spec:
  interval: 1h
  url: http://helm.penpot.app
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: penpot
spec:
  interval: 1h
  chart:
    spec:
      chart: penpot
      sourceRef:
        kind: HelmRepository
        name: penpot
      version: 0.31.0
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  install:
    remediation:
      retries: -1
  values:
    config:
      publicUri: "https://penpot.siron.casa"
      telemetryEnabled: false
      existingSecret: penpot
      secretKeys:
        apiSecretKey: PENPOT_SECRET_KEY
      flags: "enable-oidc-registration enable-login-with-oidc disable-email-verification disable-login-with-password"
      fileDataBackend: "db"

      postgresql:
        existingSecret: penpot-db-app
        host: "penpot-db-rw.penpot.svc"
        database: app
        secretKeys:
          passwordKey: password
          usernameKey: user

      redis:
        host: dragonfly-penpot.penpot.svc.cluster.local

      objectStorage:
        storageBackend: "fs"

      providers:
        oidc:
          enabled: true
          baseURI: "https://sso.siron.casa/application/o/penpot/"
          roles: ""
          rolesAttribute: ""
          scopes: "openid profile email"
          nameAttribute: nickname
          emailAttribute: email
        existingSecret: "penpot"
        secretKeys:
          oidcClientIDKey: PENPOT_OIDC_CLIENT_ID
          oidcClientSecretKey: PENPOT_OIDC_CLIENT_SECRET

    persistence:
      assets:
        existingClaim: penpot

