---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: penpot
spec:
  interval: 1h
  url: http://helm.penpot.app
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: penpot
spec:
  interval: 1h
  chart:
    spec:
      chart: penpot
      sourceRef:
        kind: HelmRepository
        name: penpot
      version: 0.38.0
  values:
    config:
      publicUri: "https://penpot.siron.casa"
      telemetryEnabled: false
      existingSecret: penpot
      secretKeys:
        apiSecretKey: PENPOT_SECRET_KEY
      flags: "enable-oidc-registration enable-login-with-oidc disable-email-verification disable-login-with-password"
      fileDataBackend: "db"

      postgresql:
        username: penpot
        password: ~
        existingSecret: "penpot"
        secretKeys:
          postgresqlUriKey: "connection_url"

      redis:
        host: dragonfly-penpot.penpot.svc.cluster.local

      objectStorage:
        storageBackend: "fs"

      providers:
        oidc:
          enabled: true
          baseURI: "https://sso.siron.casa/oauth2/openid/penpot-app/"
          roles: ""
          rolesAttribute: ""
          scopes: "openid profile email"
          nameAttribute: nickname
          emailAttribute: email
        existingSecret: "penpot-app-kanidm-oauth2-credentials"
        secretKeys:
          oidcClientIDKey: CLIENT_ID
          oidcClientSecretKey: CLIENT_SECRET

    backend:
      deploymentAnnotations:
        reloader.stakater.com/auto: "true"
      volumes:
        - name: penpot-postgres
          projected:
            defaultMode: 0400
            sources:
              - secret:
                  name: postgres-penpot-cert
                  items:
                    - key: tls.crt
                      path: tls.crt
                    - key: key.der
                      path: tls.key
        - name: root-ca
          secret:
            secretName: root-ca
            defaultMode: 0400
      volumeMounts:
        - name: penpot-postgres
          mountPath: "/var/run/secrets/postgresql"
          readOnly: true
        - name: root-ca
          mountPath: "/var/run/secrets/root-ca"
          readOnly: true


    exporter:
      deploymentAnnotations:
        reloader.stakater.com/auto: "true"

    persistence:
      assets:
        existingClaim: penpot
