---
apiVersion: kaniop.rs/v1beta1
kind: KanidmOAuth2Client
metadata:
  name: penpot-app
spec:
  displayname: Penpot
  image:
    url: https://cdn.jsdelivr.net/gh/selfhst/icons@main/png/penpot.png
  kanidmRef:
    name: sso
    namespace: sso
  origin: https://penpot.siron.casa/
  redirectUrl:
    - https://penpot.siron.casa/api/auth/oidc/callback
  preferShortUsername: true
  allowInsecureClientDisablePkce: true
  scopeMap:
    - group: penpot
      scopes:
        - openid
        - profile
        - email
        - groups
---
apiVersion: kaniop.rs/v1beta1
kind: KanidmGroup
metadata:
  name: penpot
spec:
  kanidmRef:
    name: sso
    namespace: sso
  accountPolicy:
    authSessionExpiry: 2678400
  members:
    - sironheart
