---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app memini
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/database
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: cloudnative-pg
      namespace: database
    - name: ollama
      namespace: ollama
  interval: 1h
  path: ./k8s/apps/memini/memini/app
  postBuild:
    substitute:
      APP: *app
      DATABASE_EXTENSIONS: |
        [
          { name: vector },
          { name: vchord }
        ]
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 5m
  wait: false
