---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: garage
spec:
  hostnames:
    - s3.siron.casa
    - "*.s3.siron.casa"
  parentRefs:
    - name: internal
      namespace: network
      sectionName: https
  rules:
    - backendRefs:
        - name: garage
          namespace: garage
          port: 3900
